### ISSUE TITLE
Running tasks in parallel

### ISSUE THREAD

**Issue by AppShipIt** [testdouble/scripty#10]
Continued from [Twitter](https://twitter.com/searls/status/719615850114916352).

scripty subsumes some of the functionality of [npm-run-all](https://www.npmjs.com/package/npm-run-all) with stronger conventions and separation of concerns. The only feature I see missing is optional [parallel execution](https://github.com/mysticatea/npm-run-all#run-tasks-in-parallel) of subtasks although I have no immediate use case.

**Comment by searls** [comment]
Scripty is already _so close_ to being able to do this since it's just using `async.series` [here](https://github.com/testdouble/scripty/blob/master/index.js#L14).

The trick of implementing this would be:

1. How should users flag it? A package.json-wide option would be too broad, a CLI arg would be problematic given the expectation they be forwarded in #5 and #6 -- maybe an ENV var? `SCRIPTY_PARALLEL npm run test`?
2. Testing it well sounds like work.

**Comment by AppShipIt** [comment]
> How should users flag it?

I intentionally left it out of the description 😅

> A package.json-wide option would be too broad

Agreed.

> a CLI arg would be problematic

Makes sense.

> maybe an ENV var

Too broad? I'd expect to only run aggregate tasks in parallel. The only idea I had was a naming convention like `&test` (`&` inspired by Bash to run all `test:*`).

**Comment by searls** [comment]
Ahh, considering parent/aggregate tasks specifically, that is a good point. Maybe the answer is there.

I don't feel like an ENV var is too broad if it's defined inline (since it won't stick the shell session), but the idea of tweaking the naming convention is really clever. I'm going to play with that

**Comment by searls** [comment]
Turns out that using `&` (as in `npm run &test` or `npm run test&`) blows up in mysterious ways.

Is there another character that might imply parallelism? What about `npm run test+`? That at least works?

**Comment by AppShipIt** [comment]
I didn't consider that 😣 I'm weary because of lack of precedent for any other symbol I considered. What about something literate like `test.parallel`?

**Comment by searls** [comment]
Eh at that point I'd be more comfortable with the env var. using an actual word means there's a chance someone might accidentally stumble upon it and get real confused.

**Comment by searls** [comment]
Also how about a word other than parallel? It's hard for most people to spell

**Comment by AppShipIt** [comment]
> I'd be more comfortable with the env var

Should it also be propagated to subtasks e.g. `NODE_ENV=production`?

> how about a word other than parallel

`async`?

> What about `npm run test+`

Reviewing valid characters that does look best!

**Comment by searls** [comment]
Yes, one reason I like the env var (assuming it's namespaced to scripty to avoid collision like `SCRIPTY_GO_FAST=true npm run test`) is because downstream scripts you write could alter their behavior when running in parallel to avoid any locking problems / race conditions, etc.

**Comment by searls** [comment]
Another reason I like the env var is that users wouldn't need to edit or duplicate an entry in  their package.json just to switch between parallel and not (which I often want to do, for instance, when watching, so that I can get more sane stdout across two tabs)

**Comment by boneskull** [comment]
[this](https://docs.npmjs.com/misc/config#per-package-config-settings) may be the best option

**Comment by searls** [comment]
Yeah, based on the documentation, you'd think a `config` key would be the best bet, but I'm having a really hard time successfully overriding package config entries. I think the nut of it is the `npm config` docs are mostly about modifying core npm settings at runtime, whereas that's easy to conflate with _package_ config settings, which get none of the same benefits (either the env var normalization or the `--prop_name` args). I just spent 20 minutes fighting it and gave up.

Some notes:

If my package contains:

```json
"scripts": {
    "scripty": {
      "parallel": false
    }
}
```

Then as you would hope, `process.env.npm_package_config_scripty_parallel` is set to 'false'. But once it's set in the package json, there's no apparent way to override it dynamically, making it just as blunt an instrument as always using an arbitrary ENV var.

That is to say: `npm_package_config_scripty_parallel=true npm run foo`  will still set the variable to 'false', and `NPM_PACKAGE_CONFIG_SCRIPTY_PARALLEL npm run foo` will set the var in upper case, without the case-insensitive translation suggested by the docs.
