### ISSUE TITLE
The scripty.path config is not work.

### ISSUE THREAD

**Issue by libin-code** [testdouble/scripty#103]
I set scripty.path in package.json file but it's not work. Here are my env information:

- scripty version: 2.0.0
- npm version: 8.1.0
- node version: 16.13.0

**Comment by danielgindi** [comment]
Using lerna?

**Comment by rosston** [comment]
This should be resolved in scripty 2.1.0 (via https://github.com/testdouble/scripty/pull/105). Note that you'll want to put your `scripty` config underneath a `config` key, per https://github.com/testdouble/scripty#specifying-custom-script-directories. Feel free to comment/reopen if this is not actually fixed!
