### ISSUE TITLE
quiet output

### ISSUE THREAD

**Issue by boneskull** [testdouble/scripty#28]
I'd like to suppress the echoing of the script file.

**Comment by searls** [comment]
Would you want one option that suppresses both scripty logging and stdio of the scripts themselves?

**Comment by boneskull** [comment]
Just the logging of the content of whatever script it's running

**Comment by searls** [comment]
Cool! Sounds great. Sorry for the radio silence, but I'm :+1:

**Comment by searls** [comment]
Fixed by #36.
