### ISSUE TITLE
options

### ISSUE THREAD

**Issue by boneskull** [testdouble/scripty#29]
I like the idea of this project, and I had even began writing something similar.

A common thread through several issues is "options".  One needs to be able to have greater control over `scripty`'s behavior.  See #28 for an example.

If using the `config` prop of `package.json` is problematic, perhaps a `.scriptyrc` is warranted?

Anyway, I think there hasn't been a decision made on this strategy, so here's an issue for discussion.

**Comment by searls** [comment]
We did introduce a `"scripty"` package.json entry this weekend for `"path"` and `"windowsPath"` keys in 1.4.0.

If this tool didn't depend on npm, a standalone file might make sense, but since it depends on the package.json that seems like the best place to store sticky config options
