### ISSUE TITLE
Fix travis

### ISSUE THREAD

**Issue by searls** [testdouble/scripty#3]
Build #worksforme. I suspect issues on travis are linux or pathname related.

**Comment by fyockm** [comment]
Why still bother testing for `iojs` on Travis? Perhaps add `v5` or just wait till 'v6' instead?

**Comment by searls** [comment]
Thanks. I just picked a few at random to start with, because I haven't decided what to support yet. I'll probably end up with 0.10, 4, and 5.

There are _ton_ of issues with this thing on 0.10 so I'm currently working on those

**Comment by searls** [comment]
OK, I think I've got all the 0.10 issues squared away (and can pass `npm test` locally with it).

The rest of these build failures appear to be linux vs osx issues pertaining to file permissions & fs.stats: https://travis-ci.org/testdouble/scripty/builds/121997397

**Comment by searls** [comment]
Published 1.0.1 to get the 0.10 fixes out asap while looking at the rest

**Comment by searls** [comment]
Fixed the build issues, they were:

1. Missing fixtures directories (empty on my machine so git missed them)
2. Mismatced uid/guid ACLs on other fixture files (now chmod'ing within the test)
