### ISSUE TITLE
magic

### ISSUE THREAD

**Issue by boneskull** [testdouble/scripty#31]
Scripty is kind of, well, magic.  Meaning if you are unfamiliar with Scripty, and see something like this:

```json
{
  "scripts": {
    "bump": "scripty",
    "bump:major": "scripty",
    "bump:minor": "scripty",
    "bump:patch": "scripty",
    "update": "scripty",
    "preversion": "scripty",
    "publish-please": "scripty",
    "test": "scripty",
    "test:browser": "scripty",
    "test:browser:dev": "scripty",
    "test:lint": "scripty",
    "test:node": "scripty",
    "test:nsp": "scripty"
  }
}
```

...you're not going to know what the hell is going on.

What can be done about this?

**Comment by searls** [comment]
I honestly don't know. If someone googles scripty or runs any of those commands they'll probably immediately realize what it does. 

¯\_(ツ)_/¯

**Comment by ashleygwilliams** [comment]
hey! i think this is a p good question, though i don't think the solution lies with any technical extension of `scripty`. a `Gruntfile`  or a `Brocfile` is baffling to a user unfamiliar with Broccoli or Grunt. Similarly, the appearance of any framework or platform enforced abstraction is going to be confusing to people who aren't familiar with that framework or platform.

i always recommend documenting the frameworks a project uses, as well as npm scripts in any project  that uses them. usually it's a good `README` section, and to that end, i'd do something like:

> ## npm scripts
> MyProject uses [`scripty`](https://github.com/testdouble/scripty) to organize npm scripts. the scripts are defined in the [`scripts`](/scripts) directory. In `package.json` you'll see the word `scripty` as opposed to the script content you'd expect. For more info, see [scripty's GitHub](https://github.com/testdouble/scripty).

>  {{ insert table containing script names and what they do, e.g. [this](https://github.com/ashleygwilliams/relational-node#scripts) }}

**Comment by boneskull** [comment]
@ashleygwilliams great idea.  thanks!

**Comment by searls** [comment]
Closing, I hope that #32 is sufficient for now. Thank you for the feedback, @boneskull
