### ISSUE TITLE
How well does scripty work with preinstall scripts?

### ISSUE THREAD

**Issue by greduan** [testdouble/scripty#33]
Just that, my coworker is working on some complex scripts that work during `preinstall`, how well would scripty do there?

I imagine it has to be installed as a global in that case?

**Comment by searls** [comment]
I haven't considered or tested this tbh so I have no idea

**Comment by searls** [comment]
Sorry for the terse reply last night. I probably should have followed up with "could you describe for me how you'd like it to behave"?

**Comment by greduan** [comment]
That's alright, I was just busy.

The thing is our project has some `preinstall` scripts that check that the environment is properly setup, but of course you can't use scripty in the local folder if `npm install` hasn't run before.

I was just wondering what could be a workaround for this, that's all. Obviously have the setup script outside of npm is one option, but that doesn't make it so that when you do `npm install` it runs it before installing anything.

**Comment by searls** [comment]
Closing for now because I don't think it's vitally important we answer this. If you do some work on it or have a clear proposal of what we should do (which doesn't involve asking folks to install globally), then I'm game to hear it.

**Comment by greduan** [comment]
Gotcha. If I come up with anything I'll let you know. :)
