### ISSUE TITLE
Customize "sub-scripts" separation char

### ISSUE THREAD

**Issue by fampinheiro** [testdouble/scripty#40]
Hello, awesome project.
I am evaluating this package to convert the scripts of a big project.
The problem is that the separation char used is `-`.

Currently the separation char is [hardcoded](https://github.com/testdouble/scripty/blob/master/lib/resolve-script/glob-patterns.js#L4) do you think it's possible to have a way to change this? With a package.json scripty key or something.

**Comment by searls** [comment]
It seems like `:` has emerged as the conventional separator, and I'd rather err on preferring convention over configuration.

@jasonkarns could you comment on the prolificness of this convention?

**Comment by searls** [comment]
@fampinheiro -- if we don't add this support to scripty could you grep/replace the `-` separators in your project?

**Comment by fampinheiro** [comment]
Thanks for looking into this.
I am doing that. Just wanted to reach out, maybe someone has the same approach I have.

**Comment by jasonkarns** [comment]
I'm not certain how widespread the use of `:` is. But I will say that, anecdotally, I have only encountered `:` in the wild. I think it was a bit of a carryover from Grunt as people migrated `task:target` to their npm scripts.

**Comment by texastoland** [comment]
I think this can be closed.

**Comment by jasonkarns** [comment]
@texastoland 👍
