### ISSUE TITLE
Always running child scripts in parallel on Windows

### ISSUE THREAD

**Issue by agc93** [testdouble/scripty#42]
## Scenario

If I have my `package.json` like so:

```json
"scripts": {
    "server:a": "scripty",
    "server:b": "scripty",
    "server": "scripty"
}
```

and my scripts:

```shell
.
|scripts-win/
-|server/
--|a.cmd
--|b.cmd
```

where both `a.cmd` and `b.cmd` always need to run in parallel.

## The issue

The documentation says I should be able to change my package.json node to:

```json
"server": "SCRIPTY_PARALLEL=true scripty"
```

which obviously won't work on Windows. I tried changing it to:

```json
"server": "set 'SCRIPTY_PARALLEL=true' && scripty"
```

but that runs them in series.

What's the recommended way of forcing tasks to run in parallel on Windows?

---

Please let me know if that's not clear or needs more information.

**Comment by tracker1** [comment]
Use [cross-env](https://www.npmjs.com/package/cross-env)

    npm i --save cross-env

then...

    "server": "cross-env SCRIPTY_PARALLEL=true scripty"

**Comment by searls** [comment]
I'd also be open to a PR implementing scheme by which we accept the arguments via package.json and merge it, a la:

```json
"scripty": {
  "parallel":  true
}
```
