### ISSUE TITLE
v1.7.0 doesn't use custom path

### ISSUE THREAD

**Issue by mstruebing** [testdouble/scripty#45]
```
"scripty": {
  "path": "../core/scripts"
}
```

This doesn't work anymore with scripty v1.7.0.
In version v1.6.\* it is working.

Edit:
It is simply ignoring the custom path and only searches for the default ones

**Comment by searls** [comment]
Hey @mstruebing -- that sounds bad. I think the only change was #39 by @Schoonology -- would you mind taking a look at it, Mr. Schoon?

**Comment by sospedra** [comment]
+1

**Comment by searls** [comment]
Sorry about this — waiting for someone to resolve #46 on windows prior to merge

**Comment by searls** [comment]
Landed in 1.7.1 -- finally just bit the bullet and set up a fresh Windows environment for you.

That will be one 💰 please.
