### ISSUE TITLE
Pass arguments after `--` through to the script 

### ISSUE THREAD

**Issue by deanius** [testdouble/scripty#5]
Since https://github.com/npm/npm/issues/3494, if I want to pass args to the script run by `npm run` (as distinct from passing args to `npm`), I pass them after a `--`.

`npm run test -- --grep 'specific test'     #<- these are args for mocha, not for npm`

**Comment by deanius** [comment]
```
npm run test -- --foo bar # test command is `scripty` in package.json

> project@1.0.0 test /Users/deanius/src/project
> scripty "--foo" "bar"

Executing "/project/scripts/test.sh":

> #!/bin/bash
> echo $@
>
```

Nothing is echoed - scripty should pass its arguments through, and docs should 
show that this use case is supported.

**Comment by searls** [comment]
It looks like what's happening is that npm is indeed passing those args to scripty and then scripty is dutifully doing nothing with them, since it doesn't look at ARGV. I suspect the fix is to just pass whatever args it receives on to the script it invokes via spawn

**Comment by searls** [comment]
Alright and just to create _even more work for you_, the appveyor windows build is now passing. Any new example scripts in the integration tests need to be provided in the new fixture directories for windows (with `process.platform` conditionals for any divergent assertions). See https://github.com/testdouble/scripty/commit/757d16edb1e94af9ac388a8a7db9018292ff9b11 for an example
