### ISSUE TITLE
Support script/ along with scripts/ by default

### ISSUE THREAD

**Issue by jasonkarns** [testdouble/scripty#52]
[GitHub's ScriptsToRuleThemAll](https://github.com/github/scripts-to-rule-them-all/
) is picking up steam as a conventional way of having scripts in a standard location across different language stacks. They use `script/` as their conventional directory.

And anecdotally, a lot of nix devs I know seem to default to putting their shell scripts in `script/` as well.

I don't know if script/ is some long standing convention of sysadmins or a recent conventional, but it's seemingly more common than scripts/ as a directory.

I know that the script directory can be configured manually, but convention would be better. And since `script/` is the same as `scripts/` in spirit ;), I propose we also allow script/ to be used by default, without the manual configuration. Implementation would just use `script/` as a fallback. (Or perhaps _prefer_ `script/`?) I think odds of repos having both `script/` and `scripts/` is virtually nil, so I don't foresee any issue with accepting either.

I'd also support migrating towards `script/` as a default, and doing away with `scripts/` at some point in the future. But supporting both for a while would allow for backwards compatibility.

**Comment by searls** [comment]
:+1: I'd support this. In fact, before reading this, I would have assumed we already named it `script`. 

Would merge a PR that just looked up both `scripts` and `script` (and `script-win`, I guess)

**Comment by texastoland** [comment]
👍🏽 I like this.
