### ISSUE TITLE
Custom path for certain scripts?

### ISSUE THREAD

**Issue by jwhitmarsh** [testdouble/scripty#55]
Is it possible to have a custom path for certain scripts? I'm thinking via an environment variable or something. The use case is to have a shared scripts module, but also custom scripts for a project. An example package.json:

```json
  "scripts": {
    "test": "scripty",
    "start": "scripty",
    "shared-script": "CUSTOM_SCRIPTY_PATH=./node_modules/shared-scripts/scripts scripty",
    "another-shared-script": "CUSTOM_SCRIPTY_PATH=./node_modules/shared-scripts/scripts scripty"
  },
```

**Comment by searls** [comment]
This is not supported. I'd recommend just symlinking in the expected/conventional location to where you want them to be found
