### ISSUE TITLE
Revive builtIn scripts resolver

### ISSUE THREAD

**Issue by texastoland** [testdouble/scripty#58]
You removed `builtIn` scripts in 17520b50c556f7916796f1ec9098d5e2924c01b2. It'd be useful in my project to expose base scripts that dependent packages can override (I'll summarize better when it's not so late). It would only require changing 1) `builtIn` scripts to be resolved relative to `node_modules` and 2) add an option named something like `preset`.

**Comment by searls** [comment]
I'm open to this so long as it can be accomplished in a way that absolutely does not cause anyone's existing scripty use to accidentally invoke a shared script or for some bad actor to cleverly trigger a script by a scripty user. Arbitrary script execution of stuff in your node_modules (e.g. postinstall security fiascos) is appropriately scary enough as it is.

**Comment by texastoland** [comment]
I'll PR It's as safe as configuring `path`. The idea is to run default scripts from a specified "preset" package but still create your own locally. Kind of the way create-react-app works. I'll PR today.
