### ISSUE TITLE
Way to specify a folder for scripts

### ISSUE THREAD

**Issue by eisisig** [testdouble/scripty#8]
I'm intrigued! But for me to be able to use it I would have to specify another folder name and/or path where scripty would look for scripts. Would that make sense?

`./scripts/*` => `./core/scripts/*` etc... I don't want to add another namespace infront of the scripts names `core:dev:app`

**Comment by searls** [comment]
:+1: this sounds good to me. I think we should probably implement this with a `scripty` entry in the package.json file.

``` json
"scripty": {
  "scriptsDir": "core"
}
```

Scripty, in turn, will search that directory instead of "scripts". Sound good?

**Comment by searls** [comment]
Note: We'll probably also need a configuration option for windows scripts, as well

**Comment by eisisig** [comment]
Thats sounds like the way to go. We have a few "custom" configs in our pacakge.json (babel, ava etc...)

**Comment by searls** [comment]
Yeah, that seems to be the way things are going, and seems doubly appropriate when the cli is coupled npm to begin with.

**Comment by gvn** [comment]
Suggestion: `path` instead of `scriptsDir`

**Comment by searls** [comment]
@gvn -- whatever I pick I'll want to be careful about it. As mentioned above, we're only talking about scripts in the user directory, but we'll need a way to specify either/or of `scripts` and `scripts-win`, so `path` is probably too generic. I also want to be careful of introducing too generic of an option name as I start to noodle on the potential needs of a future plugin module system.

**Comment by searls** [comment]
FYI, I went with `path` and `windowsPath` after lots of test rewriting of the internal names.

Landed in 1.4.0
