### ISSUE TITLE
Options won't work with npm >= 7

### ISSUE THREAD

**Issue by FredericEspiau** [testdouble/scripty#93]
Hello,

because of RFC21 : https://github.com/npm/rfcs/blob/latest/implemented/0021-reduce-lifecycle-script-environment.md

`npm_package_*` are no longer exported in the environment variables

No idea what the fix should be

Thanks for the hard and awesome work on this!

**Comment by searls** [comment]
cc/ @jasonkarns for visibility and/or 🧂

**Comment by jasonkarns** [comment]
@searls too late. I was railing about this on Twitter when this behavior was announced (while npm7 was still in beta)

https://twitter.com/JessTelford/status/1258549958728286208
https://twitter.com/jasonkarns/status/1293736534403887106

https://github.com/npm/rfcs/pull/183

**Comment by FredericEspiau** [comment]
So, are you going to to something about this ?

**Comment by rosston** [comment]
I'm not likely to have time to work on this soon, but I want to note what I've found about fixing this so far.

Here's what I think options compatibility with npm 7 will require:
* Figure out how to handle implementing and testing this in both npm 6 and 7; npm 6 is still the default for LTS versions of node (v10, v12, and v14 as of this writing), so I think it makes sense to support both versions
* Code that uses `npm_package_scripty_*` (just [lib/load-option.js](https://github.com/testdouble/scripty/blob/ee9a109b7e8b20db4123893b62677f911d4cf649/lib/load-option.js#L46)) will need to be updated to also/instead use `npm_package_json` (per the [RFC](https://github.com/npm/rfcs/blob/latest/implemented/0021-reduce-lifecycle-script-environment.md#detailed-explanation)) and then parse the file from that env var to find scripty options
* Update several test files ([lib/load-option.test.js](https://github.com/testdouble/scripty/blob/ee9a109b7e8b20db4123893b62677f911d4cf649/lib/load-option.test.js), [test/safe/modules-test.js](https://github.com/testdouble/scripty/blob/ee9a109b7e8b20db4123893b62677f911d4cf649/test/safe/modules-test.js), [test/safe/relative-path-loading.js](https://github.com/testdouble/scripty/blob/ee9a109b7e8b20db4123893b62677f911d4cf649/test/safe/relative-path-loading.js)) that specify `npm_package_scripty_*` env vars to also/instead work based on `npm_package_json`

**Comment by JerryC8080** [comment]
+1

**Comment by wroughtec** [comment]
Seems to be an even bigger issue with yarn 2+ as currently does not have `npm_package_json` available

**Comment by rosston** [comment]
This should be resolved in scripty 2.1.0 (via https://github.com/testdouble/scripty/pull/105). Note that you'll want to put your `scripty` config underneath a `config` key, per [the updated README](https://github.com/testdouble/scripty/blob/main/README.md). Feel free to comment/reopen if this is not actually fixed!
